# Generated by Django 5.1.1 on 2024-09-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subplan_subplanfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
