# Generated by Django 5.1.1 on 2024-09-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_subplan_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubPlanFeature',
            new_name='SubPlanFeatures',
        ),
    ]
