# Generated by Django 5.1.1 on 2024-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subplan_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeatures',
            name='subplan',
        ),
        migrations.AddField(
            model_name='subplanfeatures',
            name='subplans',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
