# Generated by Django 5.1.1 on 2024-09-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_subplanfeatures_subplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplanfeatures',
            old_name='subplans',
            new_name='subplan',
        ),
    ]
