# Generated by Django 5.1.1 on 2024-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_subscriber_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("detail", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("img", models.ImageField(upload_to="trainers/")),
            ],
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="img",
            field=models.ImageField(null=True, upload_to="subs/"),
        ),
    ]
