# Generated by Django 5.1.1 on 2024-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_trainer_alter_subscriber_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="pwd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
