# Generated by Django 5.1.1 on 2024-09-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_notify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notify",
            name="status",
        ),
    ]
