# Generated by Django 5.1.1 on 2024-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_assignsubscriber_subscriber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subplan",
            name="validity_days",
            field=models.IntegerField(null=True),
        ),
    ]
