# Generated by Django 5.1.1 on 2024-09-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_subplan_validity_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="reg_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
