# Generated by Django 5.1.1 on 2024-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_subscription_reg_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banners",
            options={"verbose_name_plural": "Banners"},
        ),
        migrations.AlterModelOptions(
            name="notifuserstatus",
            options={"verbose_name_plural": "Notification Status"},
        ),
        migrations.AlterModelOptions(
            name="subplanfeatures",
            options={"verbose_name_plural": "Plan Features"},
        ),
        migrations.AddField(
            model_name="trainer",
            name="facebook",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="pinterest",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="twitter",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="youtube",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
