# Generated by Django 5.1.1 on 2024-09-23 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_trainer_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt", models.IntegerField()),
                ("amt_date", models.DateField()),
                ("remarks", models.TextField()),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.trainer"
                    ),
                ),
            ],
        ),
    ]
