# Generated by Django 5.1.1 on 2024-09-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_trainernotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifTrainerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "notif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.trainernotification",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.trainer"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trainer Notification Status",
            },
        ),
    ]
