# Generated by Django 5.1.1 on 2024-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_trainermsg"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainermsg",
            options={"verbose_name_plural": "Messages for Trainer"},
        ),
        migrations.AlterField(
            model_name="trainermsg",
            name="user_type",
            field=models.CharField(blank=True, default="admin", max_length=100),
        ),
    ]
