# Generated by Django 5.1.1 on 2024-09-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_alter_trainermsg_options_alter_trainermsg_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainermsg",
            name="user_type",
        ),
    ]
