# Generated by Django 5.1.1 on 2024-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_trainersubscriberreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_img", models.ImageField(upload_to="app_logos/")),
            ],
        ),
    ]
